version: '3.8'

networks:
  public:
    external: true
    name: net-pastis-hosting-docker_public

services:
  php:
    image: ${IMAGE_NAME:-ghcr.io/trivoallan/yazoo:v0.1.0}
    networks:
      - default
      - public
    labels:
      - traefik.docker.network=net-pastis-hosting-docker_public
      - traefik.enable=true
      - traefik.http.routers.yazoo-php.entrypoints=http
      - traefik.http.routers.yazoo-php.rule=Host(`yazoo.constructions-incongrues.net`)
      - traefik.http.services.yazoo-php.loadbalancer.server.port=80
    environment:
      APP_ENV: prod
      APP_HOSTNAME: yazoo.constructions-incongrues.net
      CADDY_GLOBAL_OPTIONS: auto_https off
      MARIADB_HOST: yazoo-db
      SERVER_NAME: http://yazoo.constructions-incongrues.net
    env_file:
      - .env
      - stack.env
    restart: unless-stopped

  db:
    container_name: yazoo-db
    image: mariadb:${MARIADB_VERSION:-10.8.38}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
      - stack.env
    restart: unless-stopped

volumes:
  db_data: {}
