version: '3.8'

networks:
  public:
    external: true
    name: net-pastis-hosting-docker_public

services:
  php:
    image: ghcr.io/constructions-incongrues/yazoo:latest
    networks:
      - default
      - public
    labels:
      - traefik.docker.network=net-pastis-hosting-docker_public
      - traefik.enable=true
      - traefik.http.routers.yazoo-php.entrypoints=http
      - traefik.http.routers.yazoo-php.rule=Host(`{{ APP_HOSTNAME }}`)
      - traefik.http.services.yazoo-php.loadbalancer.server.port=80
    environment:
      APP_ENV: "{{ APP_ENV }}"
      APP_HOSTNAME: "{{ APP_HOSTNAME }}"
      APP_SECRET: "{{ APP_SECRET }}"
      CADDY_EMAIL: "{{ CADDY_EMAIL }}"
      CADDY_EXTRA_CONFIG: "{{ CADDY_EXTRA_CONFIG }}"
      CADDY_GLOBAL_OPTIONS: "{{ CADDY_GLOBAL_OPTIONS }}"
      DIRECTUS_EMAIL: "{{ DIRECTUS_EMAIL }}"
      DIRECTUS_PASSWORD: "{{ DIRECTUS_PASSWORD }}"
      MARIADB_CHARSET: "{{ MARIADB_CHARSET }}"
      MARIADB_DATABASE: "{{ MARIADB_DATABASE }}"
      MARIADB_HOST: "{{ MARIADB_HOST }}"
      MARIADB_PASSWORD: "{{ MARIADB_PASSWORD }}"
      MARIADB_PORT: "{{ MARIADB_PORT }}"
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: "{{ MARIADB_USER }}"
      MARIADB_VERSION: "{{ MARIADB_VERSION }}"
      SERVER_NAME: "http://{{ APP_HOSTNAME }}"
      YOUTUBE_API_KEY: "{{ YOUTUBE_API_KEY }}"
    restart: unless-stopped

  db:
    container_name: "{{ MARIADB_HOST }}"
    image: "mariadb:{{ MARIADB_VERSION }}"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_CHARSET: "{{ MARIADB_CHARSET }}"
      MARIADB_DATABASE: "{{ MARIADB_DATABASE }}"
      MARIADB_HOST: "{{ MARIADB_HOST }}"
      MARIADB_PASSWORD: "{{ MARIADB_PASSWORD }}"
      MARIADB_PORT: "{{ MARIADB_PORT }}"
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: "{{ MARIADB_USER }}"
      MARIADB_VERSION: "{{ MARIADB_VERSION }}"
    restart: unless-stopped

volumes:
  db_data: {}
