version: '3.8'

services:
  php:
    build:
      context: ..
      target: frankenphp_dev
    volumes:
      - ../:/app
      - ../frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ../frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ../:/workspaces
    depends_on:
      - db
    env_file: ../.env
    restart: unless-stopped

  db:
    image: mariadb:10.3.38
    restart: unless-stopped
    volumes:
      - ../etc/yazoo.sql.gz:/docker-entrypoint-initdb.d/00_yazoo.sql.gz
      - db_data:/var/lib/mysql
    env_file: ../.env

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file: ../.env
    network_mode: service:php

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.17.1
    restart: always
    depends_on:
      - n8n-import
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=dev
      - WEBHOOK_URL=https://localhost/
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - ../etc/n8n:/tmp/workflows
      - n8n_data:/home/node/.n8n
    network_mode: service:php

  n8n-import:
    image: docker.n8n.io/n8nio/n8n:1.17.1
    restart: on-failure
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=dev
      - WEBHOOK_URL=https://localhost/
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - ../etc/n8n:/tmp/workflows
      - n8n_data:/home/node/.n8n
    command:
      - import:workflow
      - --separate
      - --input=/tmp/workflows/

volumes:
  db_data: {}
  n8n_data: {}
