version: '3.8'

services:
  php:
    build:
      context: .
      target: frankenphp_dev
    environment:
      HTTP_PORT: 8000
      HTTPS_PORT: 4430
      HTTP3_PORT: 4430
    volumes:
      - ../../:/workspaces

  db:
    image: mariadb:10.3.38
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: yazoo
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data:
