name: Continuous Delivery

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - '*'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
      - next

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: false
          target: frankenphp_prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          cache-to: type=inline

      - name: Push
        uses: docker/build-push-action@v5.1.0
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref_name, 'next')
        with:
          context: .
          push: true
          target: frankenphp_prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          cache-to: type=inline

      - name: Deploy (yazoo-next)
        uses: carlrygart/portainer-stack-deploy@v1.3.0
        if: github.ref == 'refs/heads/next'
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: yazoo-next
          stack-definition: etc/stack.yaml
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          template-variables: ${{ secrets.YAZOO_NEXT_VARS }}

      - name: Deploy (yazoo-main)
        uses: carlrygart/portainer-stack-deploy@v1.3.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: yazoo-main
          stack-definition: etc/stack.yaml
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          template-variables: ${{ secrets.YAZOO_PROD_VARS }}
