on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.please.outputs.releases_created }}
      prs_created: ${{ steps.please.outputs.prs_created }}
      tag_name: ${{ steps.please.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
