on:
  push:
    branches:
      - main
      - '*'

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.please.outputs.release_created }}
      tag_name: ${{ steps.please.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: php

  build:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      pushed: ${{ needs.release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: $s{{ needs.release.outputs.release_created }}
          target: frankenphp_prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: yazoo-main
      uses: carlrygart/portainer-stack-deploy@v1.3.0
      if: ${{ needs.build.outputs.pushed }}
      with:
        portainer-host: ${{ secrets.PORTAINER_HOST }}
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        stack-name: yazoo-main
        stack-definition: etc/stack.yaml
        image: ghcr.io/${{ github.repository }}:latest
        template-variables: ${{ secrets.YAZOO_PROD_VARS }}
